# Generated by Django 5.1 on 2024-10-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='context',
            new_name='content',
        ),
    ]
